services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_web
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - ./services/rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped